/****** Script for SelectTopNRows command from SSMS  ******/
CREATE   VIEW [crm].[DocLine] AS
SELECT l.[LineId]
      ,l.[DocId]
      ,ISNULL(l.[LineName],p.[PLUName]) AS [LineName]
      ,l.[PLU]
      ,l.[LineTypeId]
	  ,l1.[LineTypeName]
      ,l.[LineDate]
      ,l.[DueDate]
      ,l.[DeliveryDate]
      ,l.[Qty]
      ,l.[Price]
      ,l.[LineTaxId]
	  ,l.[Qty]*l.[Price] AS [GrossAmount]
	  ,l.[Qty]*l.[Price]*l2.[PlineTax] AS [VAT]
	  ,l.[Qty]*l.[Price]+l.[Qty]*l.[Price]*l2.[PlineTax] AS [Amount]
	  ,l2.[PlineTax]
      ,l2.[LineTaxName]
	  ,l.[IsRegistered]
      ,l.[IsDelivered]
      ,l.[ResourceId]
      ,l.[Retention]
      ,l.[RetAcc]
	  ,p.[SalesAcc]
	  ,c.[AccountId] AS [CNAE]
  FROM [crm].[Line] l
  INNER JOIN [crm].[LineType] l1 ON l.[LineTypeId]=l1.[LineTypeId]
  INNER JOIN [crm].[LineTax] l2 ON l.[LineTaxId]=l2.[LineTaxId]
  LEFT JOIN [crm].[Product] p ON l.[PLU]=p.[PLU]
  LEFT JOIN [crm].[Cnae] c ON p.CnaeId=c.[CnaeId]